import type { Metadata } from "next";
import "./globals.css";
import { NavigationMenuDemo } from "@/components/Navbar01";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-center mt-5">
          <NavigationMenuDemo />
        </div>
        {children}
      </body>
    </html>
  );
}
